baseURL = 'https://tvs.vote/'
languageCode = 'en-us'
title = 'TVS - Trustless Voting System'

[params]
CompanyName = 'TVS'
repoName = 'Trustless-Voting-System-tvs-'
description = 'A cryptographic voting system that achieves voter privacy, vote integrity, and public verifiability without requiring trust in any single authority.'
github = 'https://github.com/jasonsutter87/Trustless-Voting-System-tvs-'

[environments.development]
baseURL = 'http://localhost:1313/'

[environments.production]
baseURL = 'https://tvs.vote/'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Products'
    url = '/products/'
    weight = 2
  [[menu.main]]
    name = 'Demo'
    url = '/demo/'
    weight = 3
  [[menu.main]]
    name = 'Docs'
    url = '/docs/'
    weight = 4
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/jasonsutter87/Trustless-Voting-System-tvs-'
    weight = 5

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
